name: PHP CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:              # Allow manual trigger (for deploy)

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP syntax check
        run: find public -name "*.php" -exec php -l {} \;

  deploy:
    if: github.event_name == 'workflow_dispatch'  # Only run deploy when manually triggered
    needs: php-lint                                # Wait for lint to succeed first
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy only public/ folder to server
        run: |
          rsync -avz --delete --no-perms --no-owner --no-group --no-times \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/
